#!/usr/bin/env python
# encoding: utf-8

import metadata
import json
import datetime

dthandler = lambda obj: obj.date().isoformat() if isinstance(obj, datetime.datetime) else None

if __name__ == '__main__':
    import sys

    with open(sys.argv[1], 'r') as inputfile:
        print json.dumps(metadata.extract(inputfile), default=dthandler)
